#!/bin/sh


########################################################################
# install packages and dependencies
#

wget -O /tmp/opencv1_1.0.0-1_i386.deb http://solitaire.diamond.cs.cmu.edu/opencv1_1.0.0-1_i386.deb
wget -O /tmp/opendiamond_3.2.1_i386.deb http://solitaire.diamond.cs.cmu.edu/opendiamond_3.2.1_i386.deb
wget -O /tmp/dermfind_1.0.0_20080208_771.deb http://solitaire.diamond.cs.cmu.edu/dermfind_1.0.0_20080208_771.deb
wget -O /tmp/hosts http://solitaire.diamond.cs.cmu.edu/dermfind_hosts
sudo dpkg -i /tmp/opencv1_1.0.0-1_i386.deb
sudo dpkg -i /tmp/opendiamond_3.2.1_i386.deb
sudo dpkg -i /tmp/dermfind_1.0.0_20080208_771.deb
sudo apt-get -f -y install 
sudo apt-get -y install g++


########################################################################
# setup initial Diamond state
#

mkdir -p ~/.diamond/

wget -O ~/.diamond/name_map http://solitaire.diamond.cs.cmu.edu/dermfind_name_map
wget -O ~/.diamond/gid_map http://solitaire.diamond.cs.cmu.edu/dermfind_gid_map

echo "DATAROOT /home/diamond/" > ~/.diamond/diamond_config
echo "INDEXDIR /home/diamond/" >> ~/.diamond/diamond_config
echo "CACHEDIR /home/diamond/" >> ~/.diamond/diamond_config
echo "DATATYPE NATIVE" >> ~/.diamond/diamond_config


########################################################################
# setup initial SnapFind state
#

sudo cat /tmp/hosts >> /etc/hosts

########################################################################
# Cleanup.. Will this help?
#

sudo apt-get clean
rm -f /tmp/*.deb
sudo rm -f /var/cache/apt/partial/*
sudo rm -f /var/lib/apt/lists/*_Packages
sudo rm -f /var/lib/apt/lists/*_Sources
sudo rm -f /var/lib/apt/lists/*_Release
