#!/bin/bash
#
#  Kimberley
#
#  Copyright (c) 2008-2009 Carnegie Mellon University
#  All rights reserved.
#
#  Kimberley is free software: you can redistribute it and/or modify
#  it under the terms of version 2 of the GNU General Public License
#  as published by the Free Software Foundation.
#
#  Kimberley is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Kimberley. If not, see <http://www.gnu.org/licenses/>.
#

########################################################################
# Create a new floppy disk image (FAT32) to be used during
# dekimberlize as a persistent storage device.
#

output_file="/tmp/floppy"

megabytes=10

usage()
{
        echo "usage: `basename $0` [-o file] [-s size-in-MB]"
}


while getopts ":o:s:h" Option
do
    case $Option in
        o)
            output_file=$OPTARG
            ;;
        s)
            megabytes=$OPTARG
            declare -i megabytes
            ;;
        h)
            usage
            exit 0
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done
shift $(($OPTIND-1))

size=`echo "scale=1; 1024*$megabytes" | bc`


echo
echo "Creating floppy '$output_file' of size $megabytes MB.."
echo
/sbin/mkdosfs -v -c -C $output_file $size
echo


exit 0
