#!/bin/bash

########################################################################
# Create a new floppy disk image (FAT32) to be used during
# dekimberlize as a persistent storage device.
#

output_file="/tmp/floppy"

megabytes=10

usage()
{
        echo "usage: `basename $0` [-o file] [-s size-in-MB]"
}


while getopts ":o:s:h" Option
do
    case $Option in
        o)
            output_file=$OPTARG
            ;;
        s)
            megabytes=$OPTARG
            declare -i megabytes
            ;;
        h)
            usage
            exit 0
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done
shift $(($OPTIND-1))

size=`echo "scale=1; 1024*$megabytes" | bc`


echo
echo "Creating floppy '$output_file' of size $megabytes MB.."
echo
/sbin/mkdosfs -v -c -C $output_file $size
echo


exit 0
