#!/bin/sh


########################################################################
# install packages and dependencies
#

wget -O /tmp/pathfind.tar.gz http://solitaire.diamond.cs.cmu.edu/pathfind_config/pathfind.tar.gz
tar -xzf /tmp/pathfind.tar.gz -C /tmp


########################################################################
# Setup initial Diamond state
#

mkdir -p ~/.diamond/

wget -O ~/.diamond/name_map http://solitaire.diamond.cs.cmu.edu/pathfind_config/name_map
wget -O ~/.diamond/gid_map http://solitaire.diamond.cs.cmu.edu/pathfind_config/gid_map
wget -O ~/.diamond/diamond_config http://solitaire.diamond.cs.cmu.edu/pathfind_config/diamond_config
wget -O ~/.diamond/NEWSCOPE http://solitaire.diamond.cs.cmu.edu/pathfind_config/newscope

