#!/bin/sh


########################################################################
# install packages and dependencies
#

wget -O /tmp/opencv1_1.0.0-1_i386.deb http://solitaire.diamond.cs.cmu.edu/opencv1_1.0.0-1_i386.deb
wget -O /tmp/opendiamond_3.2.1_i386.deb http://solitaire.diamond.cs.cmu.edu/opendiamond_3.2.1_i386.deb
wget -O /tmp/snapfind_1.2.5_i386.deb http://solitaire.diamond.cs.cmu.edu/snapfind_1.2.5_i386.deb
sudo apt-get -y update
sudo dpkg -i /tmp/opencv1_1.0.0-1_i386.deb
sudo dpkg -i /tmp/opendiamond_3.2.1_i386.deb
sudo dpkg -i /tmp/snapfind_1.2.5_i386.deb
sudo apt-get -f -y install 


########################################################################
# Setup initial Diamond state
#

mkdir -p ~/.diamond/

wget -O ~/.diamond/name_map http://solitaire.diamond.cs.cmu.edu/snapfind_name_map
wget -O ~/.diamond/gid_map http://solitaire.diamond.cs.cmu.edu/snapfind_gid_map

echo "DATAROOT $HOME" > ~/.diamond/diamond_config
echo "INDEXDIR $HOME" >> ~/.diamond/diamond_config
echo "CACHEDIR $HOME" >> ~/.diamond/diamond_config
echo "DATATYPE NATIVE" >> ~/.diamond/diamond_config


########################################################################
# Setup initial SnapFind state
#

mkdir -p ~/.diamond/snapfind/
echo "PLUGIN_DIR      /usr/local/diamond/lib" > ~/.diamond/snapfind/snapfindrc
