#!/bin/sh


########################################################################
# install packages and dependencies
#

wget -O /tmp/opendiamond-3.3.0-1.i386.rpm http://solitaire.diamond.cs.cmu.edu/opendiamond-3.3.0-1.i386.rpm
wget -O /tmp/snapfind-1.2.6.tar.gz http://solitaire.diamond.cs.cmu.edu/snapfind-1.2.6.tar.gz

sudo rpm -Uvh /tmp/opendiamond-3.3.0-1.i386.rpm
sudo tar -xzf /tmp/snapfind-1.2.6.tar.gz -C /


########################################################################
# Setup initial Diamond state
#

mkdir -p ~/.diamond/

wget -O ~/.diamond/name_map http://solitaire.diamond.cs.cmu.edu/snapfind_name_map
wget -O ~/.diamond/gid_map http://solitaire.diamond.cs.cmu.edu/snapfind_gid_map

echo "DATAROOT $HOME" > ~/.diamond/diamond_config
echo "INDEXDIR $HOME" >> ~/.diamond/diamond_config
echo "CACHEDIR $HOME" >> ~/.diamond/diamond_config
echo "DATATYPE NATIVE" >> ~/.diamond/diamond_config


########################################################################
# Setup initial SnapFind state
#

mkdir -p ~/.diamond/snapfind/
echo "PLUGIN_DIR      /usr/local/diamond/lib" > ~/.diamond/snapfind/snapfindrc
