#!/bin/bash
#
#  Kimberley
#
#  Copyright (c) 2008-2009 Carnegie Mellon University
#  All rights reserved.
#
#  Kimberley is free software: you can redistribute it and/or modify
#  it under the terms of version 2 of the GNU General Public License
#  as published by the Free Software Foundation.
#
#  Kimberley is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Kimberley. If not, see <http://www.gnu.org/licenses/>.
#

########################################################################
# Create a new X server which will contain only the application
# Use a 5:3 screen ratio, maximizing the size of the X dimension
# on the display
#
export DISPLAY=:0
x_res=$(xdpyinfo | awk '/dimensions:/ {print $2}' | head -1 | cut -dx -f1)
y_res=$(expr $x_res \* 3 / 5)
resolution="${x_res}x${y_res}"


########################################################################
# Set up VNC server to allow remote connection to new X server
#
scale=`echo "770/${x_res}"`

echo "Local resolution: $resolution"
echo x11vnc -once -localhost -display :0 -scale $scale 

x11vnc -once -localhost -display :0 -scale $scale > /tmp/x11vnc_port 2> /tmp/x11vnc_err &


########################################################################
# Begin running dekimberlize in this new VM asap to load application
#
xscreensaver-command -deactivate

dekimberlize "$@"

#xscreensaver-command -activate

########################################################################
# Once dekimberlize finishes, take down processes brought 
# up by display_setup
#

killall x11vnc
rm -f /tmp/x11vnc_port
